version: "3.9"

services:
    web:
        build: nginx
        ports:
          - 80:80
          - 443:443
        depends_on:
          - api
    api:
      build: backend
      expose:
        - 8000
      ports:
        - 8000:8000